### PR TITLE
Enable persistent session

### LINKED ISSUE #116: Add persistent session handling
From https://github.com/pow-auth/pow_site/issues/8#issuecomment-566847318:

> `PowAssent` doesn't support `PowPersistentSession`. My thinking is that the provider authorizes access, and it only really makes sense that the authorization is only valid for the current session. You usually want to verify that the access token still works after a while or refresh token can be used to re-auth. This could be made easier though by having something similar to `PowPersistentSession` in `PowAssent` that will remember the current user and redirect the user to re-auth when seen again without an active session. That would be seamless with most providers.

### PR DESCRIPTION
**Pull request by danschultzer**
Resolves #116

This just uses the PowPersistentSession extension. The dev enables it by passing `persistent_session: true` param for the authorization url phase.

### CODE REVIEW

**Comment by alukito** [comment]
Will this be merged in v0.4.6?

**Comment by danschultzer** [comment]
I've released `v0.4.6` to get the rest going, not completely sure about this one yet.

**Comment by alukito** [comment]
Does this mean without using Persistent Session, the session timeout will be using Pow.Plug.Session timeout which defaults to 30 minutes? 

Our client asks for 30 days expiration session using Google Auth. Do you have any suggestion?

**Comment by danschultzer** [comment]
In that case this PR is what you need.

My alternative idea as mentioned in #116 is to keep a cookie that only stores what provider was used for authorization, and will redirect the user back to that provider to reauth again if there is no active session. I feel this is the more appropriate way to deal with provider authorization rather than setting a persistent session. For many providers, if you already are authenticated there it would be pass-thru. Would this work in your case, or would you need to keep persistent session in your platform?

**Comment by alukito** [comment]
I see, so the idea in #116 is whenever there is no active session, pow_assent will try to renew the session by contacting providers, and if users are still logged in, then it will be a seamless login without the users need to press any buttons. When users are not logged in, then they need to reauth on the provider's page. 

Is my assumption right about users don't need to do anything? If it is, then I agree with you that it is more appropriate.

**Comment by danschultzer** [comment]
Yup, the user doesn't need to do anything. The user will be redirected for auth at the provider, but most providers would just redirect the user back if they already have consented the first time. Since authentication happens at the provider, I feel it also makes more sense to let the provider handle persistent session rather than having it being part of PowAssent.

> Edit: Do you think it is good idea to fork and use this PR while #116 is not ready yet?

If you need it now yeah. If you know how to deal with plugs and `before_send` callback then you could also call `PowPersistentSession.Plug.create/2` for the `:callback` controller action when a user is present.

**Comment by alukito** [comment]
I've used plugs before so I'll check `:callback` controller action first to make sense of it. Thanks for the pointers, really appreciate it.

**Comment by mplatts** [comment]
Is there a workaround in the mean time?

**Comment by mplatts** [comment]
+1 for merging this. Currently half my users login with Facebook, the other email. So only half get the persistent session. A lot a complaints show that people seem to expect staying logged in these days.

**Comment by danschultzer** [comment]
I've opened #178 that supports both versions (reauthorization with provider or using PowPersistentSession), and it works very well 😄

**Pull request closed without merging**
